chore: installer

diff --git a/setup/pi/setup-teslausb b/setup/pi/setup-teslausb
--- a/setup/pi/setup-teslausb
+++ b/setup/pi/setup-teslausb
@@ -35,6 +35,7 @@ function setup_progress () {
   fi
   echo "$@"
 }
+export -f setup_progress
 
 function curlwrapper () {
   setup_progress "curl $*" > /dev/null
@@ -124,7 +125,14 @@ copy_script setup/pi/configure-ssh.sh /tmp
 setup_progress "Early SSH configuration applied"
 
 function dehumanize () {
-  echo $(($(echo "$1" | sed 's/GB/G/;s/MB/M/;s/KB/K/;s/G/*1024M/;s/M/*1024K/;s/K/*1024/')))
+  local value
+  value=$(echo "$1" | tr '[:lower:]' '[:upper:]')
+  if ! [[ "$value" =~ ^[0-9]+([KMG])?$ ]]
+  then
+    echo "STOP: invalid size '$1'. Use values like 500M or 4G" >&2
+    return 1
+  fi
+  echo $(($(echo "$value" | sed 's/GB/G/;s/MB/M/;s/KB/K/;s/G/*1024M/;s/M/*1024K/;s/K/*1024/')))
 }
 
 REBOOT=false
@@ -1080,8 +1088,6 @@ function cmd_diagnose {
     sed -E 's/\o033\[0;32m//' |
     sed -E 's/\o033\[0m//'
 }
-
-export -f setup_progress
 
 INSTALL_DIR=${INSTALL_DIR:-/root/bin}
 if [ "$INSTALL_DIR" != "/root/bin" ]
